[package]
name = "pb-rs"
version = "0.7.0"
description = "A converter from proto files into quick-protobuf compatible rust module"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
keywords = ["protobuf", "parser", "quick-protobuf"]
license = "MIT"
readme = "README.md" 
repository = "https://github.com/tafia/quick-protobuf"

[dependencies]
nom = "4.1.0"
clap = "2.32.0"
failure = "0.1.1"
failure_derive = "0.1.1"
log = "0.4.4"
env_logger = "0.5.13"

[dev-dependencies]
walkdir = "2.2.5"
